"""empty message

Revision ID: aa5786e35e99
Revises: e5453d8a5570
Create Date: 2023-10-12 12:27:26.665225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5786e35e99'
down_revision = 'e5453d8a5570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    with op.batch_alter_table('task_user_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_by_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_to_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_to_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_user_link', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_to_id')
        batch_op.drop_column('user_by_id')

    op.create_table('association',
    sa.Column('user_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='association_task_id_fkey'),
    sa.ForeignKeyConstraint(['user_by_id'], ['users.id'], name='association_user_by_id_fkey'),
    sa.ForeignKeyConstraint(['user_to_id'], ['users.id'], name='association_user_to_id_fkey')
    )
    # ### end Alembic commands ###
